// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlVZvmpW6Kmm6bF8r2A-FsVPhlobaUVHk',
    appId: '1:234512144441:web:38e4753ea8b6e94f06d5e8',
    messagingSenderId: '234512144441',
    projectId: 'fix-my-nest-dbaea',
    authDomain: 'fix-my-nest-dbaea.firebaseapp.com',
    storageBucket: 'fix-my-nest-dbaea.appspot.com',
    measurementId: 'G-DF2G86MMR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUgEOArHRk6jyfm2YfKUl9kg7cSaEGIT0',
    appId: '1:234512144441:android:ff5e9f5ef1c9cb3006d5e8',
    messagingSenderId: '234512144441',
    projectId: 'fix-my-nest-dbaea',
    storageBucket: 'fix-my-nest-dbaea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7t7hiK1mz_UDaFiXUWe5oww8KTQUbOQ4',
    appId: '1:234512144441:ios:f17b9f70c7c4d83806d5e8',
    messagingSenderId: '234512144441',
    projectId: 'fix-my-nest-dbaea',
    storageBucket: 'fix-my-nest-dbaea.appspot.com',
    iosBundleId: 'com.example.fixMyNestUser',
  );
}
